# Generated by Django 4.0.4 on 2022-06-15 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0002_rename_user_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='User',
            new_name='user',
        ),
    ]
