# Generated by Django 4.0.4 on 2022-06-15 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0005_rename_user_post_person'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='person',
            new_name='username',
        ),
    ]
