# Generated by Django 4.0.4 on 2022-06-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0006_rename_person_post_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
