# Generated by Django 4.0.4 on 2022-06-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0007_rename_username_post_firstname_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
    ]
