# Generated by Django 4.0.4 on 2022-06-18 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myblogapp', '0008_remove_user_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='firstname',
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=1000000),
        ),
        migrations.AlterField(
            model_name='post',
            name='heading',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
